spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/payment?createDatabaseIfNotExist=true&serverTimezone=Asia/Seoul&useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: password
  thymeleaf:
    cache: false

  cloud:
    stream:
      kafka:
        binder:
          brokers: pkc-gq2xn.asia-northeast3.gcp.confluent.cloud:9092
          configuration:
            security:
              protocol: SASL_SSL
            sasl:
              jaas:
                config: org.apache.kafka.common.security.plain.PlainLoginModule required username='2VLYZNOZZXP77H2Q' password='{{5icwWkLVF9uRMPX73ren9J75XETdw2lqloqEqk3Ihque/TBF3HPVypHqBRWUzy7K}}'
              mechanism: PLAIN
            client:
              dns:
                lookup: use_all_dns_ips
          required-acks: all
          auto-create-topics: false
        bindings:
          send-out-0:
            producer:
              record-metadata-channel: payment-result
      bindings:
        send-out-0:
          destination: payment
          group: payment-service

management:
  endpoints:
    web:
      exposure:
        include: bindings


PSP:
  toss:
    secretKey: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
    url: https://api.tosspayments.com


logging:
  level:
    org:
      springframework:
        web: DEBUG
        r2dbc: DEBUG
        transaction: DEBUG